### ISSUE TITLE
Support for QT <5.6

### ISSUE THREAD

**Issue by pkerpedjiev** [tycho-kirchner/shournal#1]
Hey, this looks like an awesome tool and I would love to try it out. Unfortunately I had a really hard time getting Qt >= 5.6 installed on an OS X Docker container. You mentioned in the docs that it wouldn't be hard to adopt shournal to use Qt >= 5.3. If that's the case, can you consider this one vote for implementing that?

**Comment by tycho-kirchner** [comment]
Hi, and thanks for having opened the first issue for this project (; 
Glad to hear that you want to give it a try. While it's not hard to make shournal compatible with Qt >=5.3 it surely is a bit of work. Therefore, since you are already using docker containers I would like to ask what Linux-distribution you are running inside it? I just tested with a debian:stretch image 

https://hub.docker.com/_/debian

where Qt is new enough out of the box and it worked flawlessly (after adding the required capabilites). 
If you have a good reason to run an older Linux-distribution within docker please let me know.

**Comment by pkerpedjiev** [comment]
Can I turn that around and ask what Dockerfile you're using?

For the distribution, I was using `ubuntu:bionic`. I just tried `debian:stretch` with the following Dockerfile:

```
from debian:stretch

RUN apt-get update && apt-get install -y g++ cmake make qtbase6-dev libqt5sql5-sqlite uuid-dev libcap-dev uuid-runtime

CMD bash
```

And get

```
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package qtbase6-dev
The command '/bin/sh -c apt-get update && apt-get install -y g++ cmake make qtbase6-dev libqt5sql5-sqlite uuid-dev libcap-dev uuid-runtime' returned a non-zero code: 100
```

**Comment by tycho-kirchner** [comment]
You were almost there (;
Actually the message
`E: Unable to locate package qtbase6-dev`
pretty much says it. Where does this 6 come from? In shournal's main README the package name is `qtbase5-dev`. After using below Dockerfile shournal compiled successfully for me:
```
from debian:stretch
RUN apt-get update && apt-get install -y g++ cmake make qtbase5-dev libqt5sql5-sqlite uuid-dev libcap-dev uuid-runtime
CMD bash
```

**Comment by pkerpedjiev** [comment]
Wow, I have no idea where that 6 came from 🤔 Sorry about the distraction. I got the Docker container built. I have another question but for that I'll open another issue.

Thanks for your help!
