### ISSUE TITLE
Error running shournal --exec

### ISSUE THREAD

**Issue by pkerpedjiev** [tycho-kirchner/shournal#2]
I built `shournal` in a Docker container using the following Dockerfile:

```
from debian:stretch

RUN apt-get update && apt-get install -y g++ cmake make qtbase5-dev libqt5sql5-sqlite uuid-dev libcap-dev uuid-runtime

COPY . shournal
WORKDIR shournal/build
RUN cmake  .. # defaults to -DCMAKE_BUILD_TYPE=Release
RUN make
RUN make install

RUN groupadd shournalmsenter

CMD bash
```

When I go into the container (`docker run -it shournal`) and try to execute `shournal`, I get an error like this:

```
root@ecaf28f8a679:/shournal/build# shournal --exec sh -c 'echo hi > foo'
shournal-run 2019-08-29 20:14:05 critical: unshare failed (1): Operation not permitted
```

Am I doing something wrong? Maybe I missed a step in the installation?

**Comment by tycho-kirchner** [comment]
The README currently only describes the installation steps for a full system (or virtual machine), I will add a docker section soon. Until then: The problem is that shournal requires more capabilites than are set by default in a typical docker container. In particular the additional capabilities 
`SYS_ADMIN,SYS_PTRACE,SYS_NICE` are required. To add the capabilites when initially running an image, you can
`docker run -it --cap-add SYS_ADMIN --cap-add SYS_PTRACE --cap-add SYS_NICE  $IMAGE_ID` 
(or, use `--privileged`).
To add those capabilities to an existing container, please see also 
[this so-question](https://stackoverflow.com/a/45752205)

Sorry for the hassle :|

**Comment by pkerpedjiev** [comment]
That did the trick. Thanks!
